In [7]:
import torch
import numpy as np

In [3]:
x = torch.ones(3,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.__version__

'1.7.0+cu101'

#Tensors

######A Tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array. it is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement of NumPy to use the power of GPUs.

######Tensors are a type of data structure used in linear algebra and like vetors and matrices, you can calculate arithmetic operations with tensors. 

In [8]:
lst = [3,4,5,6]
arr = np.array(lst)
arr.dtype

dtype('int64')

#Convert Numpy To Pytorch Tensors

In [9]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [10]:
## Indexing similar to numpy
tensors[:2]

tensor([3, 4])

In [22]:
#2D arrays
arr2d = np.arange(0,15).reshape(5,3)
tensord2d = torch.tensor(arr2d)
print(arr2d)
print(tensord2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])


In [24]:
#indexing for 2D

print(tensord2d [:,0])
print(tensord2d[:,0:2])

tensor([ 0,  3,  6,  9, 12])
tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])


In [12]:
# Disadvantage of from_numpy. The array and tensor uses the same memory Location
#If u change anything in Tensors it will directly affectv the numpy arr

tensors[3] = 100
print("new tensor:", tensors)
print("new Arr:", arr)

new tensor: tensor([  3,   4,   5, 100])
new Arr: [  3   4   5 100]


In [15]:
## Prevent this by using torch.tensor

tensor_arr = torch.tensor(arr)
print("old tensor:", tensor_arr)

tensor_arr[3] = 20
print("new tensor:", tensor_arr)
print("old Arr:", arr)



old tensor: tensor([  3,   4,   5, 100])
new tensor: tensor([ 3,  4,  5, 20])
old Arr: [  3   4   5 100]


In [16]:
## Zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [20]:
torch.ones(2,3, dtype=torch.float64)


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

#Arithmetic Operations

In [25]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [26]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [27]:
#if u want to store output in a new tensor

c = torch.zeros(3) #we took 1D array because of output we are getting by adding a and b

torch.add(a,b,out=c)

print(c)

tensor([ 7.,  9., 11.])


In [28]:
# Here add a&b and also sum all the output together

torch.add(a,b).sum()

tensor(27.)

#Dot Products and Mult Operations

In [29]:
x = torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype = torch.float)

x.mul(y)

tensor([12., 20., 30.])

In [30]:
#Dot Product--- 3*4+4*5+5*6 = 62

x.dot(y)

tensor(62.)

In [31]:
#Matrix multiplication

x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)


In [32]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [33]:
#shortform for matmul

torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [35]:
#Another option for multiplication
x@y

tensor([[55., 53.],
        [90., 92.]])

#Back Propogation Using Pytorch

##Compute Derivatives

####x^n--------> derivative-------> n*x^n-1

####y = x^2

####Derivative of y w.r.t x
####dy/dx = 2*x^2-1 ----> 2x





In [45]:
x = torch.tensor(4.0, requires_grad=True) #requires_grad=True --> gradient should be initialized when we want to do back propogation
x

tensor(4., requires_grad=True)

In [46]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [47]:
#After backpropogation by solving equation the value of x == 8
#To get that Back propogation --> y =2*x
#by using Torch

y.backward()


print(x.grad)

tensor(8.)


####More...........

In [48]:
#Only Tensors of floating point dtype can require gradients

lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst, requires_grad=True)

torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [49]:
# y = x**3 + x**2
# So, if x is 2 then y = 2**3+2**2 = 8+4 = 12

y = torch_input**3+torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [50]:
z=y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [51]:
# Derivative of y = x**3 + x**2 is y = 3x**2+2x
# if x = 2 then y = 3*2**2+2*2 = 16

#So, lets create a backward propogation

z.backward()
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])